# Generated by Django 5.0.7 on 2024-07-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_remove_productcategories_category_id_parent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
